DATA:
  USE_MOTION: True
  SIZE: 288
  TRAIN_JSON_PATH: "data2022/train-tracks_nlpaug.json"
  EVAL_JSON_PATH: "data2022/val_nlpaug.json"
  CROP_AREA: 1.6666667 ## new_w = CROP_AREA* old_w



MODEL:
  NAME: "dual-stream"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "./weights/roberta-large"
  IMG_ENCODER: "efficientnet-b2"
  car_idloss: False
  mo_idloss: False
  share_idloss: False
TRAIN:
  BATCH_SIZE: 64

TEST:
  QUERY_JSON_PATH: "data2022/test-queries_nlpaug.json"
  RESTORE_FROM: "./logs/single_baseline_aug1_lr0.01_freeze0_warm40_decay-120/checkpoint_best_eval.pth"

